{% set name = "ckmeans-1d-dp" %}
{% set version = "4.3.4.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ckmeans_1d_dp-{{ version }}.tar.gz
  sha256: efc973c661cabf77ea48161823709a113fa70c1c1c20800c724b003b5d4b8f5e

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - python
    - setuptools >=42
    - wheel
    - pybind11 >=2.10.0
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - ckmeans_1d_dp
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A python interface for the Ckmeans.1d.dp R package
  home: https://github.com/AldenMB/Ckmeans.1d.dp
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AldenMB
